version: '2'

services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    environment:
      SSH_KEY: '<YOUR _KEY_HERE>'
      GIT_REPO: 'git@github.com:<YOUR_ACCOUNT>/<YOUR_REPO>.git'
      GIT_EMAIL: 'void@ngd.io'
      GIT_NAME: '<YOUR_NAME>'
